### PR TITLE
Update plugin.yml

### PR DESCRIPTION
**Pull request by erkam2002**

### CODE REVIEW

**Comment by matthew4444** [comment]
Hi

**Comment by matthew4444** [comment]
Hry
Stop ur brealing ruled.. no pull requests

**Comment by flaxues** [comment]
What is wrong with this @matthew4444 he just wants to help!

**Comment by matthew4444** [comment]
He does hes pull fequested anthoet plugin

**Comment by erkam2002** [comment]
Can i make pull request or not?

**Comment by matthew4444** [comment]
HE JUST PULLD REQUSRDTED ANTHOER PLUGIN

**Comment by matthew4444** [comment]
Umm yas if ur on the team,wanns be on the team?

**Comment by erkam2002** [comment]
Yes

**Comment by flaxues** [comment]
@matthew4444 Ok we need to talk!

**Comment by matthew4444** [comment]
K

**Comment by flaxues** [comment]
go on gitter

**Comment by erkam2002** [comment]
I am from germany

**Comment by matthew4444** [comment]
K and k

**Comment by erkam2002** [comment]
How join i gitter chat ?

**Comment by matthew4444** [comment]
https://gitter.im/matthew4444/NetherManiacsKingdom

**Pull request merged**
